language: cpp
compiler: gcc
dist: xenial
sudo: required
notifications:
  email:
    recipients:
    - mchehab@kernel.org
    on_success: change
    on_failure: always
cache:
  directories:
  - $HOME/.ccache
  - $HOME/pbuilder-bases
matrix:
  include:
  - os: linux
    env: TARGET_OS=xenial-gtk2
  - os: linux
    env: TARGET_OS=xenial-gtk3
  - os: linux
    env: TARGET_OS=debian-sid
  - os: linux
    compiler: clang
    env: TARGET_OS=debian-sid
#  - os: windows
#    cache: false
#    env: TARGET_OS=pc
before_install:
- "${TRAVIS_BUILD_DIR}/travis/${TRAVIS_OS_NAME}.${TARGET_OS}.before_install"
install:
- "${TRAVIS_BUILD_DIR}/travis/${TRAVIS_OS_NAME}.${TARGET_OS}.install"
script:
- "${TRAVIS_BUILD_DIR}/travis/${TRAVIS_OS_NAME}.${TARGET_OS}.script"
after_script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then ccache -s; fi
